name: Update Image in the Kube.yaml
on:
  repository_dispatch:
    types: [update-image-fe]
jobs:
  update-image-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Image Version kube.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'kube-fe/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: 041551109803.dkr.ecr.ap-southeast-1.amazonaws.com/${{ github.event.client_payload.image }}
          branch: main
          message: "Update Image Version to ${{ github.event.client_payload.image }}"